package com.example.jdbcdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.jdbcdemo.domain.Person;

public class PersonManager {

	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTablePerson = "CREATE TABLE Person(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(20), yob integer)";

	private PreparedStatement addPersonStmt;
	private PreparedStatement deletePersonStmt;
	private PreparedStatement deleteAllPersonsStmt;
	private PreparedStatement updatePersonStmt;
	private PreparedStatement getAllPersonsStmt;

	private Statement statement;

	public PersonManager() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTablePerson);

			addPersonStmt = connection
					.prepareStatement("INSERT INTO Person (name, yob) VALUES (?, ?)");
			deleteAllPersonsStmt = connection
					.prepareStatement("DELETE FROM Person");
			deletePersonStmt = connection
					.prepareStatement("DELETE FROM Person WHERE name = ?");
			getAllPersonsStmt = connection
					.prepareStatement("SELECT id, name, yob FROM Person");
			updatePersonStmt = connection
					//Nowe wpierw, potem szukane.
					.prepareStatement("UPDATE Person SET name = ? where name = ?");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}

	void clearPersons() {
		try {
			deleteAllPersonsStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public int addPerson(Person person) {
		int count = 0;
		try {
			addPersonStmt.setString(1, person.getName());
			addPersonStmt.setInt(2, person.getYob());

			count = addPersonStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}
	
	public int deletePerson(String name){
		int count = 0;
		try {
			deletePersonStmt.setString(1, name);
			count = deletePersonStmt.executeUpdate();
		}
		catch (SQLException e){
			e.printStackTrace();
		}
		return count;
	}
	
	public void updatePerson(String searchedName, String toSet){
		try {
			updatePersonStmt.setString(1, toSet);
			updatePersonStmt.setString(2, searchedName);
			
			updatePersonStmt.executeUpdate();
		}
		catch (SQLException e){
			e.printStackTrace();
		}
	}
	

	public List<Person> getAllPersons() {
		List<Person> persons = new ArrayList<Person>();

		try {
			ResultSet rs = getAllPersonsStmt.executeQuery();

			while (rs.next()) {
				Person p = new Person();
				p.setId(rs.getInt("id"));
				p.setName(rs.getString("name"));
				p.setYob(rs.getInt("yob"));
				persons.add(p);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return persons;
	}

}
